#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 22 13:32:06 2022

@author: ashlee
"""

import pandas as pd
import numpy as np




df = pd.read_csv("E2.csv")

df1 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E2.csv")